"""Prompts module"""
from .agent_prompts import (
    ORCHESTRATOR_SYSTEM_PROMPT,
    SPENDING_ANALYZER_SYSTEM_PROMPT,
    CARD_EVALUATOR_SYSTEM_PROMPT,
    RECOMMENDATION_SYNTHESIZER_SYSTEM_PROMPT
)

__all__ = [
    "ORCHESTRATOR_SYSTEM_PROMPT",
    "SPENDING_ANALYZER_SYSTEM_PROMPT",
    "CARD_EVALUATOR_SYSTEM_PROMPT",
    "RECOMMENDATION_SYNTHESIZER_SYSTEM_PROMPT"
]
